### ISSUE TITLE
Node-fibers errors

### ISSUE THREAD

**Issue by ryanhovland** [pstadler/flightplan#100]
I'm getting node fibers errors when trying to run a flightplan: 

.../node_modules/flightplan/node_modules/fibers/fibers.js:16
        throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe
              ^
Error: `.../node_modules/flightplan/node_modules/fibers/bin/darwin-x64-v8-3.28/fibers.node` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (.../node_modules/flightplan/node_modules/fibers/fibers.js:16:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (.../node_modules/flightplan/lib/index.js:3:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

Not sure if this is a fibers or flightplan issue, but has anyone else experienced this? I've tried re-installing both flightplan and fibers. Thanks!

**Comment by mik01aj** [comment]
did you try reinstalling `node-fibers`, as suggested in your log?

**Comment by ryanhovland** [comment]
Yeah, I tried re-installing node-fibers but it didn't help. I thought I tried this before, but I was just able to fix the issue by uninstalling flightplan and doing a fresh install.

**Comment by Marcel-Robitaille** [comment]
Thanks! Worked for me!

**Comment by genomanetwork** [comment]
This error is due to the deprecation of node-fibers for node >=16.x released on April 20, 2021.

On the [fibers](https://github.com/laverdet/node-fibers) project README:

> Update [April 13th, 2021] -- Fibers is not compatible with nodejs v16.0.0 or later. Unfortunately, v8 commit dacc2fee0f is a breaking change and workarounds are non-trivial.

Is there any plan for this issue?
