### ISSUE TITLE
setMaxListeners 

### ISSUE THREAD

**Issue by theoephraim** [pstadler/flightplan#87]
My flight is working, but near the end, it runs into an error.

Looks to be related to ssh2, but not sure exactly what is the emitter that is getting maxed out.

```
(node) warning: possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
  at new ChannelStream (/Users/theo/Breather/breather.com/node_modules/flightplan/node_modules/ssh2/lib/Channel.js:578:17)
  at /Users/theo/Breather/breather.com/node_modules/flightplan/node_modules/ssh2/lib/Channel.js:360:20
  at Parser.<anonymous> (/Users/theo/Breather/breather.com/node_modules/flightplan/node_modules/ssh2/lib/Channel.js:142:30)
  at Parser.parsePacket (/Users/theo/Breather/breather.com/node_modules/flightplan/node_modules/ssh2/lib/Parser.js:632:12)
  at Parser.execute (/Users/theo/Breather/breather.com/node_modules/flightplan/node_modules/ssh2/lib/Parser.js:249:14)
  at Socket.<anonymous> (/Users/theo/Breather/breather.com/node_modules/flightplan/node_modules/ssh2/lib/Connection.js:536:18)
  at Connection.connect (/Users/theo/Breather/breather.com/node_modules/flightplan/node_modules/ssh2/lib/Connection.js:578:16)
  at new SSH (/Users/theo/Breather/breather.com/node_modules/flightplan/lib/transport/ssh.js:54:20)
  at /Users/theo/Breather/breather.com/node_modules/flightplan/lib/flight/remote.js:15:25
  at EventEmitter.prompt.start (/Users/theo/Breather/breather.com/node_modules/flightplan/node_modules/prompt/lib/prompt.js:74:38)
  at /Users/theo/Breather/breather.com/node_modules/flightplan/lib/transport/index.js:312:16
  at Object.Transport.prompt.self.next (/Users/theo/Breather/breather.com/node_modules/flightplan/lib/transport/index.js:277:7)
  at /Users/theo/Breather/breather.com/node_modules/flightplan/lib/transport/index.js:325:13
  at task (/Users/theo/Breather/breather.com/node_modules/flightplan/lib/transport/index.js:354:5)
  at Shell.Transport.waitFor (/Users/theo/Breather/breather.com/node_modules/flightplan/lib/transport/index.js:359:10)
  at Shell.prompt (/Users/theo/Breather/breather.com/node_modules/flightplan/lib/transport/index.js:307:17)
  at /Users/theo/Breather/breather.com/flightplan.coffee:35:19
  at /Users/theo/Breather/breather.com/node_modules/flightplan/lib/flight/local.js:16:7
```

**Comment by pstadler** [comment]
Hi Theo

I've never seen this before. Can you post the context of line 35 in `flightplan.coffee`? It seems to be local connection, right?

**Comment by theoephraim** [comment]
so line 35 is just a local prompt. It errors out way later down in the deployment.
```
...
plan.local 'deploy', (local) ->
  # confirm deployment to production
  if plan.runtime.target == 'production'
    input = local.prompt('Are you sure you want to deploy to production? [yes/no]')
    if input.indexOf('yes') == -1
      plan.abort('user canceled deploy')
...
```

the full plan is below. Also notable, I'm using this exact same plan on 2 other repos and it doesnt seem to be a problem there :\
```
plan = require 'flightplan'
moment = require 'moment-timezone'
_ = require 'lodash'
nconf = require 'nconf'

# TODO: move to /lib like the others
require './src/run-init'

USER = 'breather'
NUM_DEPLOYS = 5
SUBDOMAIN = nconf.get('BREATHER_SUBDOMAIN')
REPO = nconf.get('REPO_NAME')
NO_FRONTEND = !!nconf.get('NO_FRONTEND')

ssh_key = nconf.get('BREATHER_SSH_KEY') || "#{process.env.HOME}/.ssh/id_rsa"
deploy_branch = 'master'

# SERVERS
plan.target 'staging', _.map nconf.get('IP:staging').split(' '), (ip) ->
  host: ip
  username: USER
  privateKey: ssh_key

plan.target 'production', _.map nconf.get('IP:production').split(' '), (ip) ->
  host: ip
  username: USER
  privateKey: ssh_key


# TASKS
plan.local 'deploy', (local) ->

  # confirm deployment to production
  if plan.runtime.target == 'production'
    input = local.prompt('Are you sure you want to deploy to production? [yes/no]')
    if input.indexOf('yes') == -1
      plan.abort('user canceled deploy')

    local.log("Pushing master to #{SUBDOMAIN}.breather.com")

  # on staging, deploy the current branch
  else
    git_dirty = local.exec('git diff --shortstat')
    if git_dirty.stdout
      plan.abort('Please commit your local changes and push them to github to deploy')

    git_local_commit = local.exec('git rev-parse HEAD').stdout
    git_remote_commit = local.exec('git rev-parse @{u}').stdout

    if git_local_commit != git_remote_commit
      plan.abort('push local commits to github to deploy')

    current_branch = local.exec("git rev-parse --abbrev-ref HEAD").stdout
    deploy_branch = current_branch.replace("\n", '')

    local.log("Pushing #{deploy_branch} to #{SUBDOMAIN}.breatherdev.com")


# DEPLOY - deploys current branch for staging or master for production
plan.remote 'deploy', (remote) ->

  # set nocache to not use the old node_modules and bower libs
  no_dependency_cache = !!plan.runtime.options.nocache

  deploy_name = moment.tz('America/New_York').format('YYYY-MM-DD-HHmmss')+'-'+deploy_branch.replace(/\//g, '-')

  remote.log 'Deploying -- '+deploy_name

  remote.log 'Checking out latest from github'

  remote.exec "mkdir -p #{REPO}"

  remote.exec "cd #{REPO} && git clone git@github.com:breather/#{REPO}.git -b #{deploy_branch} #{deploy_name}"

  cd = "cd #{REPO}/#{deploy_name} &&"

  if !no_dependency_cache
    remote.log 'Using cached dependencies from last deploy (npm)'
    remote.exec "cp -R #{REPO}/current/node_modules #{REPO}/#{deploy_name}/node_modules"
    if !NO_FRONTEND
      remote.exec "mkdir #{REPO}/#{deploy_name}/assets/lib-bower"
      remote.exec "cp -R #{REPO}/current/assets/lib-bower #{REPO}/#{deploy_name}/assets/lib-bower"

  remote.log 'Installing dependencies'
  remote.exec "#{cd} npm install --production"

  if !NO_FRONTEND
    remote.log 'Building assets'
    remote.exec "#{cd} ./node_modules/.bin/grunt build"

    remote.log 'Deploying assets'
    remote.exec "#{cd} ./node_modules/.bin/grunt deploy-assets"

  remote.log 'Relinking new deployment'
  remote.exec "ln -snf ~/#{REPO}/#{deploy_name} ~/#{REPO}/current"

  remote.log 'Reloading application (zero-downtime)'
  remote.exec "pm2 reload all"

  remote.log "Deleting old deploys (last #{NUM_DEPLOYS} are saved)"
  remote.exec "cd #{REPO} && rm -rf `ls -td 201* | awk 'NR>#{NUM_DEPLOYS}'`"


# ROLLBACK - rolls back and restarts
plan.remote 'rollback', (remote) ->

  deploys = remote.exec("cd #{REPO} && ls -td 201*").stdout.replace(/\n$/, '')
  deploys = deploys.split("\n")

  current_deploy = remote.exec("readlink -f #{REPO}/current").stdout
  current_deploy = current_deploy.substr(current_deploy.lastIndexOf('/')+1).replace("\n", '')

  current_index = _.indexOf(deploys, current_deploy)
  num_available = deploys.length - current_index - 1
  if num_available == 0
    plan.abort('No old deploys available to roll back to')

  rollback_num = remote.prompt("How many deploys do you want to rollback? [default: 1, max: #{num_available}]")
  if rollback_num == '' then rollback_num = 1
  rollback_num = parseInt(rollback_num)

  if rollback_num < 1 || rollback_num > num_available
    plan.abort('Invalid # of deploys to roll back')

  rollback_name = deploys[current_index + rollback_num]

  remote.log "Relinking deployment #{rollback_num} back"
  remote.exec "ln -snf ~/#{REPO}/#{rollback_name} ~/#{REPO}/current"

  remote.log 'Reloading application (zero-downtime)'
  remote.exec "pm2 reload all"


# RESTART - restarts pm2
plan.remote 'restart', (remote) ->
  remote.log 'Restarting application'
  if plan.runtime.options.force
    remote.exec 'pm2 kill'
    # spawn as many instances as we have cores on the machine
    remote.exec "cd #{REPO} && pm2 start current/app.coffee -i 0 --name \"#{REPO}\""
  else
    remote.exec "pm2 reload all"

# STATUS - shows pm2 status
plan.remote 'status', (remote) ->
  remote.exec "pm2 list"

# STATUS - shows pm2 status
plan.remote 'logs', (remote) ->
  remote.exec "pm2 logs"
```

**Comment by seybsen** [comment]
Are you using the exact same node.js version for all the projects where you are using this flight?

**Comment by pstadler** [comment]
@seybsen Thanks for catching up here, this issue went off my radar somehow.
@theoephraim is this still a problem or could you resolve it?

**Comment by pstadler** [comment]
Please reopen this issue it's still a problem.
